
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIVIDE EQUAL ID LPAREN MINUS NUMBER PLUS RPAREN TIMESE : E PLUS T\n         | E MINUS TE : TT : T TIMES F\n         | T DIVIDE FT : FF : LPAREN E RPARENF : NUMBERF : ID'
    
_lr_action_items = {'LPAREN':([0,4,7,8,9,10,],[4,4,4,4,4,4,]),'NUMBER':([0,4,7,8,9,10,],[5,5,5,5,5,5,]),'ID':([0,4,7,8,9,10,],[6,6,6,6,6,6,]),'$end':([1,2,3,5,6,12,13,14,15,16,],[0,-3,-6,-8,-9,-1,-2,-4,-5,-7,]),'PLUS':([1,2,3,5,6,11,12,13,14,15,16,],[7,-3,-6,-8,-9,7,-1,-2,-4,-5,-7,]),'MINUS':([1,2,3,5,6,11,12,13,14,15,16,],[8,-3,-6,-8,-9,8,-1,-2,-4,-5,-7,]),'RPAREN':([2,3,5,6,11,12,13,14,15,16,],[-3,-6,-8,-9,16,-1,-2,-4,-5,-7,]),'TIMES':([2,3,5,6,12,13,14,15,16,],[9,-6,-8,-9,9,9,-4,-5,-7,]),'DIVIDE':([2,3,5,6,12,13,14,15,16,],[10,-6,-8,-9,10,10,-4,-5,-7,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'E':([0,4,],[1,11,]),'T':([0,4,7,8,],[2,2,12,13,]),'F':([0,4,7,8,9,10,],[3,3,3,3,14,15,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> E","S'",1,None,None,None),
  ('E -> E PLUS T','E',3,'p_expression_plus_minus','Parser_Calculadora.py',8),
  ('E -> E MINUS T','E',3,'p_expression_plus_minus','Parser_Calculadora.py',9),
  ('E -> T','E',1,'p_expression_term','Parser_Calculadora.py',13),
  ('T -> T TIMES F','T',3,'p_term_times_divide','Parser_Calculadora.py',17),
  ('T -> T DIVIDE F','T',3,'p_term_times_divide','Parser_Calculadora.py',18),
  ('T -> F','T',1,'p_term_factor','Parser_Calculadora.py',22),
  ('F -> LPAREN E RPAREN','F',3,'p_factor_group','Parser_Calculadora.py',26),
  ('F -> NUMBER','F',1,'p_factor_number','Parser_Calculadora.py',30),
  ('F -> ID','F',1,'p_factor_id','Parser_Calculadora.py',34),
]
